/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "../pinc.h"

PCL void OnInfoRequest(pluginInfo_t *info) {
    // =====  MANDATORY FIELDS  =====
    info->handlerVersion.major = PLUGIN_HANDLER_VERSION_MAJOR;
    info->handlerVersion.minor = PLUGIN_HANDLER_VERSION_MINOR;
}

void PlayerCmd_GetIP() {

    char adrstr[128];

    client_t* cl = Plugin_SV_Cmd_GetPlayerClByHandle(Plugin_Scr_GetString(0));

    if (cl == NULL) {
        return;
    }

  Plugin_NET_AdrToStringMT(&cl->netchan.remoteAddress, adrstr, sizeof(adrstr));

	Plugin_Scr_AddString(adrstr);
}

PCL void OnScreenshotArrived(client_t* client, const char* path)
{
  char adrstr[128];
  char buf[128];

  Plugin_NET_AdrToStringMT(&client->netchan.remoteAddress, adrstr, sizeof(adrstr));

  Plugin_G_LogPrintf("SS;%s;%s;%s;%s\n",
  SV_GetGuid(NUMFORCLIENT(client), buf, sizeof(buf)),
  client->name,
  adrstr,
  path
  );

}

void PlayerCmd_tanh() {

    float number =  Plugin_Scr_GetFloat(0);

    Plugin_Scr_AddFloat(tanh(number));
}

PCL int OnInit() {
    Plugin_ScrAddFunction("getIP", &PlayerCmd_GetIP);
    Plugin_ScrAddFunction("tanh", &PlayerCmd_tanh);
    return 0;
}